# Generated by Django 3.1.3 on 2021-04-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anoop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artmodel',
            old_name='artist',
            new_name='insta_handle',
        ),
        migrations.AlterField(
            model_name='artmodel',
            name='art_work',
            field=models.ImageField(upload_to='img/%y'),
        ),
    ]
